# แยก hologram เมื่อดาเมจมีหลายประเภท
split-hologram: true

custom-font:
  enabled: false

  # unicode เพื่อปรับระยะห่างของแต่ละตัวเลข
  space: ''

  # ดาเมจกายภาพ
  normal:
    '0': ''
    '1': ''
    '2': ''
    '3': ''
    '4': ''
    '5': ''
    '6': ''
    '7': ''
    '8': ''
    '9': ''

  # ดาเมจกายภาพคริติคอล
  crit:
    '0': ''
    '1': ''
    '2': ''
    '3': ''
    '4': ''
    '5': ''
    '6': ''
    '7': ''
    '8': ''
    '9': ''

  # ดาเมจสกิล
  skill:
    '0': ''
    '1': ''
    '2': ''
    '3': ''
    '4': ''
    '5': ''
    '6': ''
    '7': ''
    '8': ''
    '9': ''